-- GENELInK Supabase database
-- Run this migration in Supabase SQL Editor or via Supabase CLI migrations.

create extension if not exists pgcrypto;

create type public.app_role as enum ('student', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  role public.app_role not null default 'student',
  created_at timestamptz not null default now()
);

create table public.lessons (
  id bigint generated by default as identity primary key,
  title text not null,
  emoji text not null default '🧬',
  color text not null default 'mint',
  objectives jsonb not null default '[]'::jsonb,
  sort_order int not null unique
);

create table public.topics (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  title text not null,
  content text not null default '',
  sort_order int not null,
  unique (lesson_id, sort_order)
);

create table public.pretest_questions (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  question text not null,
  options jsonb not null,
  correct_answer smallint not null,
  sort_order int not null,
  unique (lesson_id, sort_order)
);

create table public.pretest_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  answers jsonb not null,
  score int not null check (score >= 0),
  total_questions int not null default 5,
  started_at timestamptz not null default now(),
  submitted_at timestamptz not null default now()
);

create table public.student_lesson_progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  pretest_completed boolean not null default false,
  completed_at timestamptz,
  unique (student_id, lesson_id)
);

create table public.student_topic_progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  topic_id bigint not null references public.topics(id) on delete cascade,
  completed_at timestamptz not null default now(),
  unique (student_id, topic_id)
);

create table public.final_exam_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  options jsonb not null,
  correct_answer smallint not null,
  lesson_id bigint references public.lessons(id) on delete set null,
  sort_order int not null unique
);

create table public.final_exam_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  answers jsonb not null,
  score int not null,
  total_questions int not null,
  submitted_at timestamptz not null default now()
);

create table public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  title text,
  created_at timestamptz not null default now()
);

create table public.ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.ai_conversations(id) on delete cascade,
  role text not null check (role in ('student', 'ai')),
  message text not null,
  created_at timestamptz not null default now()
);

-- Automatically create a student profile when a new Auth user is registered.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Explorer'),
    new.email,
    'student'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Admin helper. Run this after registering the admin account:
-- update public.profiles set role = 'admin' where email = 'admin@example.com';

-- Score monitoring view for the admin dashboard.
create or replace view public.student_score_summary
with (security_invoker = true)
as
select
  p.id as student_id,
  p.full_name,
  p.email,
  coalesce(round(avg(pa.score::numeric / nullif(pa.total_questions, 0) * 100)), 0)::int as pretest,
  coalesce((
    select round(avg(fa.score::numeric / nullif(fa.total_questions, 0) * 100))
    from public.final_exam_attempts fa
    where fa.student_id = p.id
  ), 0)::int as final,
  coalesce(round((
    avg(pa.score::numeric / nullif(pa.total_questions, 0) * 100) +
    coalesce((
      select avg(fa.score::numeric / nullif(fa.total_questions, 0) * 100)
      from public.final_exam_attempts fa
      where fa.student_id = p.id
    ), 0)
  ) / 2), 0)::int as average,
  case
    when coalesce((
      select avg(fa.score::numeric / nullif(fa.total_questions, 0) * 100)
      from public.final_exam_attempts fa
      where fa.student_id = p.id
    ), 0) >= 75 then 'Excellent'
    when coalesce((
      select avg(fa.score::numeric / nullif(fa.total_questions, 0) * 100)
      from public.final_exam_attempts fa
      where fa.student_id = p.id
    ), 0) >= 60 then 'On track'
    else 'Needs support'
  end as status
from public.profiles p
left join public.pretest_attempts pa on pa.student_id = p.id
where p.role = 'student'
group by p.id, p.full_name, p.email;

-- RLS
alter table public.profiles enable row level security;
alter table public.lessons enable row level security;
alter table public.topics enable row level security;
alter table public.pretest_questions enable row level security;
alter table public.pretest_attempts enable row level security;
alter table public.student_lesson_progress enable row level security;
alter table public.student_topic_progress enable row level security;
alter table public.final_exam_questions enable row level security;
alter table public.final_exam_attempts enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;

-- Helper functions for policies.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Profiles
create policy "Users can read their own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

create policy "Admins can read all student profiles"
on public.profiles for select
to authenticated
using (public.is_admin());

-- Public curriculum reads
create policy "Authenticated users can read lessons"
on public.lessons for select
to authenticated
using (true);

create policy "Authenticated users can read topics"
on public.topics for select
to authenticated
using (true);

create policy "Authenticated students can read pretests"
on public.pretest_questions for select
to authenticated
using (exists (
  select 1 from public.profiles where id = auth.uid() and role = 'student'
));

create policy "Authenticated students can read final exam"
on public.final_exam_questions for select
to authenticated
using (exists (
  select 1 from public.profiles where id = auth.uid() and role = 'student'
));

-- Student attempts/progress
create policy "Students can insert their pretest attempts"
on public.pretest_attempts for insert
to authenticated
with check (student_id = auth.uid());

create policy "Students can read their pretest attempts"
on public.pretest_attempts for select
to authenticated
using (student_id = auth.uid());

create policy "Students can manage their lesson progress"
on public.student_lesson_progress for all
to authenticated
using (student_id = auth.uid())
with check (student_id = auth.uid());

create policy "Students can manage their topic progress"
on public.student_topic_progress for all
to authenticated
using (student_id = auth.uid())
with check (student_id = auth.uid());

create policy "Students can insert final exam attempts"
on public.final_exam_attempts for insert
to authenticated
with check (student_id = auth.uid());

create policy "Students can read their final exam attempts"
on public.final_exam_attempts for select
to authenticated
using (student_id = auth.uid());

-- AI history
create policy "Students can manage their AI conversations"
on public.ai_conversations for all
to authenticated
using (student_id = auth.uid())
with check (student_id = auth.uid());

create policy "Students can manage messages in their conversations"
on public.ai_messages for all
to authenticated
using (exists (
  select 1 from public.ai_conversations c
  where c.id = conversation_id and c.student_id = auth.uid()
))
with check (exists (
  select 1 from public.ai_conversations c
  where c.id = conversation_id and c.student_id = auth.uid()
));

-- Admin score view access
grant select on public.student_score_summary to authenticated;

-- Seed lessons
insert into public.lessons (title, emoji, color, objectives, sort_order) values
('DNA: The Blueprint of Life', '🧬', 'mint',
 '["Explain what DNA is and why it stores genetic information.","Identify the basic structure and role of DNA.","Connect DNA to the traits of living things."]', 1),
('Genes: Tiny Instructions', '🧩', 'purple',
 '["Describe a gene as a section of DNA carrying genetic information.","Explain how genes are related to traits.","Distinguish genes from DNA as a whole."]', 2),
('Chromosomes: DNA Organized', '🧫', 'orange',
 '["Describe what chromosomes are.","Explain how DNA is organized into chromosomes.","Connect chromosomes, DNA, and genes."]', 3),
('DNA → Gene → Chromosome', '🔗', 'blue',
 '["Explain the relationship among DNA, genes, and chromosomes.","Arrange the concepts into a clear mental model.","Use the relationship to explain genetic information."]', 4),
('How Traits Are Passed On', '🌱', 'pink',
 '["Explain how genetic information is involved in inherited traits.","Describe how information can be passed from parents to offspring.","Apply genetics ideas to simple examples."]', 5);

insert into public.topics (lesson_id, title, content, sort_order)
select l.id, x.title, x.content, x.sort_order
from public.lessons l
join (values
  ('DNA: The Blueprint of Life','What is DNA?','DNA is the molecule that stores genetic information in living things.',1),
  ('DNA: The Blueprint of Life','DNA structure','DNA has a double-helix structure made from repeating building blocks called nucleotides.',2),
  ('DNA: The Blueprint of Life','DNA and genetic information','DNA stores instructions that help cells make and maintain living organisms.',3),
  ('Genes: Tiny Instructions','What is a gene?','A gene is a section of DNA that contains information used by cells.',1),
  ('Genes: Tiny Instructions','Genes and traits','Genes can influence traits such as eye color, blood type, and other characteristics.',2),
  ('Genes: Tiny Instructions','DNA vs. genes','DNA is the molecule; a gene is a specific section of that DNA.',3),
  ('Chromosomes: DNA Organized','What are chromosomes?','Chromosomes are organized structures made largely of DNA and proteins.',1),
  ('Chromosomes: DNA Organized','DNA packaging','Long DNA molecules are packaged so they can fit and function inside cells.',2),
  ('Chromosomes: DNA Organized','Chromosome–DNA–gene relationship','Genes are sections of DNA, and DNA is organized into chromosomes.',3),
  ('DNA → Gene → Chromosome','Putting the pieces together','Think of DNA as the material, genes as specific instructions, and chromosomes as organized packages.',1),
  ('DNA → Gene → Chromosome','Concept map','DNA contains genes; chromosomes organize DNA; genes help carry information for traits.',2),
  ('DNA → Gene → Chromosome','Quick challenge','Try explaining DNA, genes, and chromosomes without looking at your notes.',3),
  ('How Traits Are Passed On','Inherited traits','Some traits can be influenced by genetic information passed from parents to offspring.',1),
  ('How Traits Are Passed On','Genetic information','Genetic information is encoded in DNA and organized through genes and chromosomes.',2),
  ('How Traits Are Passed On','Trait transmission','Offspring receive genetic information from their parents, contributing to inherited characteristics.',3)
) as x(lesson_title,title,content,sort_order) on l.title = x.lesson_title;

-- Five questions per lesson. Correct answers are zero-based.
insert into public.pretest_questions (lesson_id, question, options, correct_answer, sort_order)
select l.id, q.question, q.options::jsonb, q.correct_answer, q.sort_order
from public.lessons l
join (values
('DNA: The Blueprint of Life','Which molecule stores genetic information?','["DNA","Water","Protein","Sugar"]',0,1),
('DNA: The Blueprint of Life','A gene is best described as…','["A whole cell","A section of DNA","A type of organ","A chromosome itself"]',1,2),
('DNA: The Blueprint of Life','Where is DNA organized into structures called chromosomes?','["Inside cells","Only outside cells","Only in food","Only in water"]',0,3),
('DNA: The Blueprint of Life','Which statement is most accurate?','["Genes are made of DNA","DNA is made of chromosomes","Chromosomes are made of genes only","Traits are always learned"]',0,4),
('DNA: The Blueprint of Life','Why does genetic information matter?','["It helps carry instructions for living organisms","It only describes weather","It exists only in food","It has no role in cells"]',0,5),
('Genes: Tiny Instructions','Which molecule contains genes?','["DNA","Water","Fat","Salt"]',0,1),
('Genes: Tiny Instructions','A gene is…','["A section of DNA","A complete organism","A type of tissue","A food molecule"]',0,2),
('Genes: Tiny Instructions','Genes can influence…','["Traits","The weather","Planet size","Day length"]',0,3),
('Genes: Tiny Instructions','Which is the best comparison?','["DNA is the molecule; a gene is a section of it","Genes are bigger than cells","DNA is made of organs","Genes have no genetic information"]',0,4),
('Genes: Tiny Instructions','What can a gene contain?','["Genetic information","Only water","Only minerals","No information"]',0,5),
('Chromosomes: DNA Organized','Chromosomes are mainly organized…','["DNA and proteins","Water and sugar","Only fat","Only minerals"]',0,1),
('Chromosomes: DNA Organized','Why is DNA packaged into chromosomes?','["To organize long DNA molecules","To remove all genetic information","To turn DNA into water","To stop cells from working"]',0,2),
('Chromosomes: DNA Organized','Genes are…','["Sections of DNA","Entire organs","Types of cells","Foods"]',0,3),
('Chromosomes: DNA Organized','Which order is correct?','["DNA → genes → chromosomes as organized DNA","Chromosomes → water → genes","Genes → cells → DNA only","Traits → water → chromosomes"]',0,4),
('Chromosomes: DNA Organized','Chromosomes help organize…','["Genetic material","Weather patterns","Food recipes","Muscles only"]',0,5),
('DNA → Gene → Chromosome','Which statement connects the concepts?','["Genes are sections of DNA and DNA is organized into chromosomes","Genes are unrelated to DNA","Chromosomes contain no DNA","DNA is a type of organ"]',0,1),
('DNA → Gene → Chromosome','A useful mental model is…','["DNA is material, genes are instructions, chromosomes are organized packages","DNA is weather, genes are water","Chromosomes are cells","Genes are organs"]',0,2),
('DNA → Gene → Chromosome','Where are genes found?','["Within DNA","Only in water","Outside all cells","Only in food"]',0,3),
('DNA → Gene → Chromosome','What do chromosomes organize?','["DNA","Weather","Food","Water"]',0,4),
('DNA → Gene → Chromosome','Which idea is most important?','["DNA, genes, and chromosomes are connected parts of genetic organization","They are completely unrelated","Only genes exist","Chromosomes contain no genetic information"]',0,5),
('How Traits Are Passed On','Inherited traits can involve…','["Genetic information from parents","Only weather","Only learned skills","No biological information"]',0,1),
('How Traits Are Passed On','Genetic information is encoded in…','["DNA","Water","Salt","Air"]',0,2),
('How Traits Are Passed On','Offspring can receive genetic information from…','["Parents","Only teachers","Only friends","The weather"]',0,3),
('How Traits Are Passed On','Which can contribute to inherited characteristics?','["Genes","Only exercise","Only school grades","Only weather"]',0,4),
('How Traits Are Passed On','Why do genetics help explain traits?','["Genes carry information that can influence inherited characteristics","Traits never involve biology","Genes only control weather","DNA exists only outside cells"]',0,5)
) as q(lesson_title,question,options,correct_answer,sort_order) on l.title = q.lesson_title;

-- Final exam: 10 review questions, including pretest concepts.
insert into public.final_exam_questions (question, options, correct_answer, lesson_id, sort_order)
select q.question, q.options::jsonb, q.correct_answer, l.id, q.sort_order
from public.lessons l
join (values
('DNA: The Blueprint of Life','Which molecule stores genetic information?','["DNA","Water","Protein","Sugar"]',0,1),
('Genes: Tiny Instructions','What is a gene?','["A section of DNA","A whole cell","A type of organ","A chromosome itself"]',0,2),
('Chromosomes: DNA Organized','What are chromosomes?','["Organized structures containing DNA","Types of food","Organs","Weather patterns"]',0,3),
('DNA → Gene → Chromosome','Which statement is correct?','["Genes are sections of DNA, and DNA is organized into chromosomes","Genes are unrelated to DNA","Chromosomes contain no DNA","DNA is an organ"]',0,4),
('How Traits Are Passed On','Inherited traits can involve…','["Genetic information passed from parents","Only learned behavior","Only weather","No biological information"]',0,5)
) as q(lesson_title,question,options,correct_answer,sort_order) on l.title = q.lesson_title;

insert into public.final_exam_questions (question, options, correct_answer, lesson_id, sort_order) values
('Why is DNA important to living things?','["It stores genetic information","It controls the weather","It is only a source of energy","It is an organ"]',0,1,6),
('Which relationship is correct?','["DNA contains genes; chromosomes organize DNA","Chromosomes contain no DNA","Genes are larger than chromosomes","DNA is made from organs"]',0,2,7),
('What can genes influence?','["Traits","Planet size","Weather","Time zones"]',0,3,8),
('Why does the body package DNA?','["To organize long DNA molecules","To remove genetic information","To turn DNA into water","To stop cell activity"]',0,4,9),
('What is a good way to explain genetics?','["DNA stores information, genes are sections of DNA, and chromosomes organize DNA","Genes are unrelated to DNA","Chromosomes are made of water","Traits cannot involve genetics"]',0,5,10);
