-- GENELInK's recurring weekly schedule. Additive: existing curriculum and
-- assessment tables remain the source for lessons, topics, and scores.
create table if not exists public.study_schedule (
  id bigint generated by default as identity primary key,
  name text not null,
  timezone text not null default 'Asia/Manila',
  cycle_type text not null default 'weekly' check (cycle_type = 'weekly'),
  cycle_days smallint not null default 7 check (cycle_days = 7),
  session_start time not null default time '08:00',
  session_end time not null default time '08:45',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (session_start < session_end)
);

create unique index if not exists study_schedule_one_active_idx
  on public.study_schedule (is_active)
  where is_active;

create table if not exists public.weekly_learning_schedule (
  id bigint generated by default as identity primary key,
  day_number smallint not null unique check (day_number between 1 and 7),
  activity_type text not null check (activity_type in ('pretest', 'lesson', 'post_test')),
  lesson_id bigint references public.lessons(id) on delete set null,
  title text not null,
  description text,
  sort_order smallint not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (activity_type = 'lesson' and lesson_id is not null)
    or (activity_type in ('pretest', 'post_test'))
  )
);

-- Extend the existing event log rather than creating a duplicate session log.
alter table public.student_learning_events
  add column if not exists session_date date;

alter table public.student_learning_events
  drop constraint if exists student_learning_events_event_name_check;
alter table public.student_learning_events
  add constraint student_learning_events_event_name_check
  check (event_name in (
    'session_started',
    'session_completed',
    'simulation_started',
    'prediction_submitted',
    'simulation_completed',
    'simulation_result_correct',
    'simulation_result_incorrect',
    'explanation_submitted',
    'ai_assistance_offered',
    'ai_assistance_requested',
    'application_completed',
    'reflection_completed',
    'topic_completed'
  ));

create unique index if not exists student_learning_events_one_session_start_per_day_idx
  on public.student_learning_events (student_id, session_date)
  where event_name = 'session_started';

alter table public.study_schedule enable row level security;
alter table public.weekly_learning_schedule enable row level security;

revoke all on table public.study_schedule from anon, authenticated;
revoke all on table public.weekly_learning_schedule from anon, authenticated;
grant select on table public.study_schedule to authenticated;
grant select on table public.weekly_learning_schedule to authenticated;

-- Curriculum schedule is readable by authenticated users; students cannot edit it.
drop policy if exists "Authenticated users can read active study schedule"
  on public.study_schedule;
create policy "Authenticated users can read active study schedule"
  on public.study_schedule for select
  to authenticated
  using (is_active);

drop policy if exists "Authenticated users can read active weekly activities"
  on public.weekly_learning_schedule;
create policy "Authenticated users can read active weekly activities"
  on public.weekly_learning_schedule for select
  to authenticated
  using (is_active);

insert into public.study_schedule (
  id, name, timezone, cycle_type, cycle_days, session_start, session_end, is_active
)
values (
  1,
  'GENELInK Weekly Learning Cycle',
  'Asia/Manila',
  'weekly',
  7,
  time '08:00',
  time '08:45',
  true
)
on conflict (id) do update set
  name = excluded.name,
  timezone = excluded.timezone,
  cycle_type = excluded.cycle_type,
  cycle_days = excluded.cycle_days,
  session_start = excluded.session_start,
  session_end = excluded.session_end,
  is_active = excluded.is_active,
  updated_at = now();

-- Resolve lesson IDs from the existing seeded catalog's stable sort order;
-- do not create or duplicate any lesson rows.
insert into public.weekly_learning_schedule (
  day_number, activity_type, lesson_id, title, description, sort_order, is_active
)
select
  1, 'pretest', first_lesson.id,
  'Monday — Day 1: Genetics Pre-Test',
  'Complete the existing Lesson 1 pre-test as the weekly baseline assessment.',
  1, true
from public.lessons as first_lesson
where first_lesson.sort_order = 1

union all

select
  lesson.sort_order + 1,
  'lesson',
  lesson.id,
  case lesson.sort_order
    when 1 then 'Tuesday — Day 2: Learning / Lesson 1'
    when 2 then 'Wednesday — Day 3: Learning / Lesson 2'
    when 3 then 'Thursday — Day 4: Learning / Lesson 3'
    when 4 then 'Friday — Day 5: Learning / Lesson 4'
    when 5 then 'Saturday — Day 6: Learning / Lesson 5'
  end,
  'Complete the scheduled lesson using GENELInK’s eight-phase instructional flow.',
  1,
  true
from public.lessons as lesson
where lesson.sort_order between 1 and 5

union all

select
  7, 'post_test', null,
  'Sunday — Day 7: Genetics Post-Test',
  'Complete the existing final exam as the weekly post-test.',
  1, true

on conflict (day_number) do update set
  activity_type = excluded.activity_type,
  lesson_id = excluded.lesson_id,
  title = excluded.title,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();

-- Database time and configured timezone are authoritative. This invoker RPC
-- reads only rows permitted by the caller's RLS policies and never accepts a
-- client-supplied timestamp.
create or replace function public.get_current_study_session()
returns jsonb
language plpgsql
stable
security invoker
set search_path = public, pg_temp
as $$
declare
  v_schedule public.study_schedule%rowtype;
  v_activity public.weekly_learning_schedule%rowtype;
  v_server_time timestamptz := statement_timestamp();
  v_local_time timestamp;
  v_local_date date;
  v_day_number smallint;
  v_day_name text;
  v_start_at timestamptz;
  v_end_at timestamptz;
  v_open boolean;
  v_pretest_complete boolean := false;
  v_lesson_title text;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required to read the study schedule.'
      using errcode = '42501';
  end if;

  select * into v_schedule
  from public.study_schedule
  where is_active
  limit 1;

  if not found then
    raise exception 'No active GENELInK study schedule is configured.';
  end if;

  v_local_time := v_server_time at time zone v_schedule.timezone;
  v_local_date := v_local_time::date;
  v_day_number := extract(isodow from v_local_time)::smallint;
  v_day_name := (array['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])[v_day_number];
  v_start_at := (v_local_date + v_schedule.session_start) at time zone v_schedule.timezone;
  v_end_at := (v_local_date + v_schedule.session_end) at time zone v_schedule.timezone;
  v_open := v_server_time >= v_start_at and v_server_time < v_end_at;

  select * into v_activity
  from public.weekly_learning_schedule
  where day_number = v_day_number and is_active
  limit 1;

  if not found then
    raise exception 'No active learning activity is configured for study day %.', v_day_number;
  end if;

  if v_activity.lesson_id is not null then
    select title into v_lesson_title
    from public.lessons
    where id = v_activity.lesson_id;
  end if;

  select coalesce(progress.pretest_completed, false) into v_pretest_complete
  from public.weekly_learning_schedule as pretest_day
  left join public.student_lesson_progress as progress
    on progress.lesson_id = pretest_day.lesson_id
   and progress.student_id = (select auth.uid())
  where pretest_day.day_number = 1
    and pretest_day.activity_type = 'pretest'
    and pretest_day.is_active;
  v_pretest_complete := coalesce(v_pretest_complete, false);

  return jsonb_build_object(
    'timezone', v_schedule.timezone,
    'cycle_type', v_schedule.cycle_type,
    'cycle_days', v_schedule.cycle_days,
    'session_start', to_char(v_schedule.session_start, 'HH24:MI'),
    'session_end', to_char(v_schedule.session_end, 'HH24:MI'),
    'day_number', v_day_number,
    'day_name', v_day_name,
    'session_date', v_local_date,
    'server_time', v_server_time,
    'server_time_ms', floor(extract(epoch from v_server_time) * 1000)::bigint,
    'session_start_at', v_start_at,
    'session_end_at', v_end_at,
    'before_session', v_server_time < v_start_at,
    'session_open', v_open,
    'session_closed', v_server_time >= v_end_at,
    'seconds_until_start', greatest(0, floor(extract(epoch from (v_start_at - v_server_time)))::integer),
    'remaining_seconds', greatest(0, floor(extract(epoch from (v_end_at - v_server_time)))::integer),
    'day1_pretest_complete', v_pretest_complete,
    'scheduled_activity', jsonb_build_object(
      'day_number', v_activity.day_number,
      'activity_type', v_activity.activity_type,
      'lesson_id', v_activity.lesson_id,
      'title', v_activity.title,
      'description', v_activity.description,
      'lesson_title', v_lesson_title
    )
  );
end;
$$;

revoke all on function public.get_current_study_session() from public, anon;
grant execute on function public.get_current_study_session() to authenticated;

-- Preserve the existing permissive curriculum-read policies, but add
-- restrictive schedule checks so those policies cannot expose scheduled
-- lesson/test rows through the Data API outside their current window.
drop policy if exists "Scheduled lesson topics are visible only in their session"
  on public.topics;
create policy "Scheduled lesson topics are visible only in their session"
  on public.topics as restrictive for select to authenticated
  using (
    ((select public.get_current_study_session()) ->> 'session_open')::boolean
    and ((select public.get_current_study_session()) -> 'scheduled_activity' ->> 'activity_type') = 'lesson'
    and ((select public.get_current_study_session()) -> 'scheduled_activity' ->> 'lesson_id')::bigint = lesson_id
    and ((select public.get_current_study_session()) ->> 'day1_pretest_complete')::boolean
  );

drop policy if exists "Pre-test questions are visible only in the scheduled session"
  on public.pretest_questions;
create policy "Pre-test questions are visible only in the scheduled session"
  on public.pretest_questions as restrictive for select to authenticated
  using (
    ((select public.get_current_study_session()) ->> 'session_open')::boolean
    and ((select public.get_current_study_session()) -> 'scheduled_activity' ->> 'activity_type') = 'pretest'
    and ((select public.get_current_study_session()) -> 'scheduled_activity' ->> 'lesson_id')::bigint = lesson_id
  );

drop policy if exists "Post-test questions are visible only in the scheduled session"
  on public.final_exam_questions;
create policy "Post-test questions are visible only in the scheduled session"
  on public.final_exam_questions as restrictive for select to authenticated
  using (
    ((select public.get_current_study_session()) ->> 'session_open')::boolean
    and ((select public.get_current_study_session()) -> 'scheduled_activity' ->> 'activity_type') = 'post_test'
  );

-- Students retain the existing own-row progress policy, but cannot manufacture
-- a Day 1 completion marker without a saved attempt belonging to that student.
drop policy if exists "Pre-test completion requires a saved attempt"
  on public.student_lesson_progress;
create policy "Pre-test completion requires a saved attempt"
  on public.student_lesson_progress as restrictive for insert to authenticated
  with check (
    not pretest_completed
    or exists (
      select 1 from public.pretest_attempts as attempt
      where attempt.student_id = (select auth.uid())
        and attempt.lesson_id = student_lesson_progress.lesson_id
    )
  );

drop policy if exists "Pre-test completion updates require a saved attempt"
  on public.student_lesson_progress;
create policy "Pre-test completion updates require a saved attempt"
  on public.student_lesson_progress as restrictive for update to authenticated
  using (student_id = (select auth.uid()))
  with check (
    student_id = (select auth.uid())
    and (
      not pretest_completed
      or exists (
        select 1 from public.pretest_attempts as attempt
        where attempt.student_id = (select auth.uid())
          and attempt.lesson_id = student_lesson_progress.lesson_id
      )
    )
  );

-- These triggers apply the same database-clock gate to client writes. They do
-- not alter scores; they reject attempts/progress written outside the assigned
-- activity's actual 08:00–08:45 Asia/Manila window.
create or replace function public.enforce_scheduled_learning_write()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_session jsonb;
  v_activity jsonb;
  v_type text;
  v_expected_lesson_id bigint;
  v_day_number smallint;
  v_topic_lesson_id bigint;
begin
  v_session := public.get_current_study_session();
  v_activity := v_session -> 'scheduled_activity';
  v_type := v_activity ->> 'activity_type';
  v_expected_lesson_id := nullif(v_activity ->> 'lesson_id', '')::bigint;
  v_day_number := (v_session ->> 'day_number')::smallint;

  if not coalesce((v_session ->> 'session_open')::boolean, false) then
    raise exception 'The scheduled learning session is not open.' using errcode = 'P0001';
  end if;

  if tg_table_name = 'pretest_attempts' then
    if v_type is distinct from 'pretest' or new.lesson_id is distinct from v_expected_lesson_id then
      raise exception 'Only today’s scheduled pre-test can be submitted.' using errcode = 'P0001';
    end if;
    new.submitted_at := statement_timestamp();

  elsif tg_table_name = 'student_lesson_progress' then
    if new.pretest_completed and (
      (tg_op = 'INSERT') or not old.pretest_completed
    ) then
      if v_type is distinct from 'pretest' or new.lesson_id is distinct from v_expected_lesson_id then
        raise exception 'The pre-test progress is outside its scheduled session.' using errcode = 'P0001';
      end if;
      new.completed_at := statement_timestamp();
    elsif new.completed_at is not null and (
      (tg_op = 'INSERT') or old.completed_at is null
    ) then
      if v_type is distinct from 'lesson' or new.lesson_id is distinct from v_expected_lesson_id then
        raise exception 'Lesson completion is outside today’s scheduled activity.' using errcode = 'P0001';
      end if;
      if not coalesce((v_session ->> 'day1_pretest_complete')::boolean, false) then
        raise exception 'Complete the Day 1 pre-test before completing a learning lesson.' using errcode = 'P0001';
      end if;
      new.completed_at := statement_timestamp();
    end if;

  elsif tg_table_name = 'student_topic_progress' then
    if v_type is distinct from 'lesson' or new.lesson_id is distinct from v_expected_lesson_id then
      raise exception 'Only today’s scheduled lesson can be completed.' using errcode = 'P0001';
    end if;
    if not coalesce((v_session ->> 'day1_pretest_complete')::boolean, false) then
      raise exception 'Complete the Day 1 pre-test before accessing learning topics.' using errcode = 'P0001';
    end if;
    new.completed_at := statement_timestamp();

  elsif tg_table_name = 'final_exam_attempts' then
    if v_type is distinct from 'post_test' then
      raise exception 'The post-test is only available on its scheduled day.' using errcode = 'P0001';
    end if;
    new.submitted_at := statement_timestamp();

  elsif tg_table_name = 'student_learning_events' then
    if new.event_name in ('session_started', 'session_completed') then
      if v_type = 'pretest' and new.lesson_id is distinct from v_expected_lesson_id then
        raise exception 'The pre-test session event is not today’s scheduled activity.' using errcode = 'P0001';
      elsif v_type = 'lesson' and new.lesson_id is distinct from v_expected_lesson_id then
        raise exception 'The lesson session event is not today’s scheduled activity.' using errcode = 'P0001';
      elsif v_type = 'lesson'
        and new.event_name = 'session_completed'
        and not coalesce((v_session ->> 'day1_pretest_complete')::boolean, false) then
        raise exception 'Complete the Day 1 pre-test before recording a lesson session.' using errcode = 'P0001';
      elsif v_type = 'post_test' and new.lesson_id is not null then
        raise exception 'The post-test session event must not reference a lesson.' using errcode = 'P0001';
      end if;
    else
      if v_type is distinct from 'lesson' or new.lesson_id is distinct from v_expected_lesson_id then
        raise exception 'Learning events must belong to today’s scheduled lesson.' using errcode = 'P0001';
      end if;
      if not coalesce((v_session ->> 'day1_pretest_complete')::boolean, false) then
        raise exception 'Complete the Day 1 pre-test before recording lesson activity.' using errcode = 'P0001';
      end if;
      if new.topic_id is not null then
        select lesson_id into v_topic_lesson_id
        from public.topics
        where id = new.topic_id;
        if v_topic_lesson_id is distinct from new.lesson_id then
          raise exception 'The learning event topic does not belong to its lesson.' using errcode = '23514';
        end if;
      end if;
    end if;
    new.session_day := v_day_number;
    new.session_date := (v_session ->> 'session_date')::date;
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_scheduled_learning_write() from public, anon, authenticated;

drop trigger if exists enforce_scheduled_pretest_window on public.pretest_attempts;
create trigger enforce_scheduled_pretest_window
before insert on public.pretest_attempts
for each row execute function public.enforce_scheduled_learning_write();

-- Keep the pre-test attempt and its completion marker in the same database
-- transaction so a submission just before 08:45 cannot be split by the cutoff.
create or replace function public.complete_scheduled_pretest_progress()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  insert into public.student_lesson_progress (
    student_id, lesson_id, pretest_completed, completed_at
  )
  values (
    new.student_id, new.lesson_id, true, statement_timestamp()
  )
  on conflict (student_id, lesson_id) do update set
    pretest_completed = true,
    completed_at = coalesce(
      student_lesson_progress.completed_at,
      excluded.completed_at
    );

  return new;
end;
$$;

revoke all on function public.complete_scheduled_pretest_progress() from public, anon, authenticated;

drop trigger if exists complete_scheduled_pretest_progress on public.pretest_attempts;
create trigger complete_scheduled_pretest_progress
after insert on public.pretest_attempts
for each row execute function public.complete_scheduled_pretest_progress();

drop trigger if exists enforce_scheduled_pretest_progress on public.student_lesson_progress;
create trigger enforce_scheduled_pretest_progress
before insert or update on public.student_lesson_progress
for each row execute function public.enforce_scheduled_learning_write();

drop trigger if exists enforce_scheduled_topic_progress on public.student_topic_progress;
create trigger enforce_scheduled_topic_progress
before insert or update on public.student_topic_progress
for each row execute function public.enforce_scheduled_learning_write();

drop trigger if exists enforce_scheduled_posttest_window on public.final_exam_attempts;
create trigger enforce_scheduled_posttest_window
before insert on public.final_exam_attempts
for each row execute function public.enforce_scheduled_learning_write();

drop trigger if exists enforce_scheduled_learning_event_window on public.student_learning_events;
create trigger enforce_scheduled_learning_event_window
before insert on public.student_learning_events
for each row execute function public.enforce_scheduled_learning_write();

comment on table public.study_schedule is
  'Authoritative repeating study-week configuration. Day 1 is Monday; times are interpreted in the configured timezone.';
comment on table public.weekly_learning_schedule is
  'Maps each weekday to an existing lesson or assessment without duplicating curriculum data.';
