-- Additive, student-owned learning event log for the instructional flow.
-- Does not alter or replace existing assessment/progress tables.
create table if not exists public.student_learning_events (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete set null,
  topic_id bigint references public.topics(id) on delete set null,
  event_name text not null check (event_name in (
    'simulation_started',
    'prediction_submitted',
    'simulation_completed',
    'simulation_result_correct',
    'simulation_result_incorrect',
    'explanation_submitted',
    'ai_assistance_offered',
    'ai_assistance_requested',
    'application_completed',
    'reflection_completed',
    'topic_completed'
  )),
  phase text check (phase in (
    'engage', 'explore', 'predict', 'simulate',
    'explain', 'feedback', 'apply', 'reflect'
  )),
  session_day smallint check (session_day between 1 and 7),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists student_learning_events_student_time_idx
  on public.student_learning_events (student_id, created_at desc);

create index if not exists student_learning_events_topic_idx
  on public.student_learning_events (student_id, lesson_id, topic_id, created_at desc);

alter table public.student_learning_events enable row level security;

drop policy if exists "Students can insert their own learning events"
  on public.student_learning_events;
create policy "Students can insert their own learning events"
  on public.student_learning_events for insert
  to authenticated
  with check (student_id = (select auth.uid()));

drop policy if exists "Students can read their own learning events"
  on public.student_learning_events;
create policy "Students can read their own learning events"
  on public.student_learning_events for select
  to authenticated
  using (student_id = (select auth.uid()));

-- New tables may not be exposed to the Data API automatically on newer projects.
revoke all on table public.student_learning_events from anon, authenticated;
grant select, insert on public.student_learning_events to authenticated;

revoke all on sequence public.student_learning_events_id_seq from anon, authenticated;
grant usage, select on sequence public.student_learning_events_id_seq to authenticated;

comment on column public.student_learning_events.details is
  'Minimal structured event metadata only. Do not store student free-response text here.';
